client.println("<!DOCTYPE html>");
client.println("<html lang='en'>");
client.println("<head>");
client.println("<style>");
client.println("body {");
client.println("margin: 0;");
client.println("padding: 0;");
client.println("box-sizing: border-box;");
client.println("}");
client.println("h2 {");
client.println("margin: 0;");
client.println("}");
client.println("header {");
client.println("text-align: center");
client.println("}");
client.println("header nav ul {");
client.println("list-style: none;");
client.println("padding: 0;");
client.println("}");
client.println("header nav ul li {");
client.println("display: inline-block;");
client.println("padding: 0 15px;");
client.println("}");
client.println("header nav ul li a {");
client.println("text-decoration: none;");
client.println("color: #000;");
client.println("font-size: 20px;");
client.println("letter-spacing: 2px;");
client.println("}");
client.println("section {");
client.println("height: 100vh;");
client.println("}");
client.println("section#lights {");
client.println("background-color: crimson;");
client.println("}");
client.println("section#lights #intensity_container {");
client.println("padding: 15px 0;");
client.println("}");
client.println("section#sensors {");
client.println("background-color: yellow;");
client.println("display: flex;");
client.println("align-items: center;");
client.println("justify-content: center;");
client.println("}");
client.println("section#sensors ul#sensors_data {");
client.println("font-size: 35px;");
client.println("}");
client.println("section#sensors ul#sensors_data {");
client.println("list-style: none;");
client.println("}");
client.println("</style>");
client.println("<meta charset='UTF-8'>");
client.println("<meta name='viewport' content='width=device-width, initial-scale=1.0'>");
client.println("<title>Home Automation-Lights</title>");
client.println("</head>");
client.println("<body>");
client.println("<section class='section' id='lights'>");
client.println("<div id='intensity_container'>");
client.println("<a href='/LED=100'><button class='intensity'>100%</button></a>");
client.println("<a href='/LED=75'><button class='intensity'>75%</button></a>");
client.println("<a href='/LED=50'><button class='intensity'>50%</button></a>");
client.println("<a href='LED=25'><button class='intensity'>25%</button></a>");
client.println("<a href='LED=0'><button class='intensity'>0%</button></a>");
client.println("</div>");
client.println("<a href='/LED=NOTIF'><button class='notif'>Notification</button></a>");
client.println("<div id='color_picker'>");
client.println("<input type='color' id='color'>");
client.println("<input id='red' type='text' placeholder='red'>");
client.println("<input id='green' type='text' placeholder='green'>");
client.println("<input id='blue' type='text' placeholder='blue'>");
client.println("<a href=''><button>Valid</button></a>");
client.println("</div>");
client.println("</section>");
client.println("<section class='section' id='sensors'>");
client.println("<ul id='sensors_data'>");
client.println("<div class='inline'>");
client.println("<li class='sensor'>Temperature: <p id='temperature'>25</p>°C</li>");
client.println("</div>");
client.println("<li class='sensor'>Humidity: </li>");
client.println("<li class='sensor'>Luminosité: </li>");
client.println("<li class='sensor'>Last Movement: </li>");
client.println("</ul>");
client.println("</section>");
client.println("<script>");
client.println("const hexToRGB = (hex) => {");
client.println("var c;");
client.println("if(/^#([A-Fa-f0-9]{3}){1,2}$/.test(hex)){");
client.println("c=hex.substring(1).split('');");
client.println("if(c.length==3){");
client.println("c=[c[0], c[0], c[1], c[1], c[2], c[2]];");
client.println("}");
client.println("c='0x'+c.join('');");
client.println("return [(c>>16)&255, (c>>8)&255, c&255].join(',');");
client.println("}");
client.println("throw new Error('Bad hex');");
client.println("}");
client.println("redInput = document.querySelector('#red');greenInput = document.querySelector('#green');blueInput = document.querySelector('#blue');");
client.println("colorPicker = document.querySelector('#color');");
client.println("colorPicker.addEventListener('input', () => {");
client.println("let color = colorPicker.value;");
client.println("rgbColor = hexToRGB(color);");
client.println("redInput.value = rgbColor.split(',')[0];");
client.println("greenInput.value = rgbColor.split(',')[1];");
client.println("blueInput.value = rgbColor.split(',')[2];");
client.println("})");
client.println("</script>");
client.println("</body>");
client.println("</html>");
